services:
  client:
    container_name: client_jenkins
    build: ./client
    ports:
      - "3001:3000"  # Jenkins frontend
    environment:
      - REACT_APP_YOUR_HOSTNAME=http://54.87.76.62:5001
    depends_on:
      - server

  server:
    container_name: server_jenkins
    build: ./server
    ports:
      - "5001:5000"  # Jenkins backend
    env_file:
      - ./server/.env
